AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'config/**/*.rb'
    - 'config.ru'
    - 'db/schema.rb'
    - 'Rakefile'

# https://docs.rubocop.org/rubocop/cops_style.html#styledocumentation
Style/Documentation:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_style.html#stylefrozenstringliteralcomment
Style/FrozenStringLiteralComment:
  Enabled: false
